
import Breadcrumb from "@/components/UI/Breadcrumb";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <div className="flex h-screen bg-gray-100">
      {/* Sidebar */}
      <aside className="w-64 bg-blue-800 text-white flex flex-col h-full">
        <div className="p-4 font-bold text-lg border-b border-blue-700">
          Sidebar Title
        </div>
        <nav className="flex-1 p-4">
          <ul>
            <li className="py-2 hover:bg-blue-600 px-2 rounded">
              <a href="#" className="block">Dashboard</a>
            </li>
            <li className="py-2 hover:bg-blue-600 px-2 rounded">
              <a href="#" className="block">Profile</a>
            </li>
            <li className="py-2 hover:bg-blue-600 px-2 rounded">
              <a href="#" className="block">Settings</a>
            </li>
            <li className="py-2 hover:bg-blue-600 px-2 rounded">
              <a href="#" className="block">Logout</a>
            </li>
          </ul>
        </nav>
      </aside>

      {/* Main Content */}
      <main className="flex-1 p-6 bg-white overflow-auto">
        <header className="flex justify-between items-center mb-6">
          <Breadcrumb />
          <button className="text-sm bg-blue-600 text-white py-2 px-4 rounded">
            Button
          </button>
        </header>
        <div className="content">
          {children}
        </div>
      </main>
    </div>

  );
}
